name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Build the Astro app
        run: |
          npm ci
          npm run build

      - name: Upload via SFTP to server
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          removeExtraFilesOnServer: true
          concurrency: 8
          localDir: "dist"
          remoteDir: ${{ secrets.REMOTE_DIR }}
