name: Build and Depoly

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js 20
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Build the Astro app
              run: |
                  npm install
                  npm run build

            - name: Upload via SFTP to server
              uses: wangyucode/sftp-upload-action@v2.0.2
              with:
                  host: ${{ secrets.HOST }}
                  port: ${{ secrets.PORT }}
                  username: ${{ secrets.USER }}
                  password: ${{ secrets.PASSWORD }}
                  compress: true
                  removeExtraFilesOnServer: true
                  localDir: "dist"
                  remoteDir: ${{ secrets.REMOTE_DIR }}
