name: Build and Depoly

on:
    push:
        branches: [main]

jobs:
    deploy-frontend:
        name: Build and Deploy FH Kalender
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js 18
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Build the Astro app
              run: |
                npm install
                npm run build

            - name: Upload via SFTP
              uses: wlixcc/SFTP-Deploy-Action@v1.2.4
              with:
                  server: ${{ secrets.SFTP_SERVER }}
                  port: ${{ secrets.SFTP_PORT }}
                  username: ${{ secrets.SFTP_USERNAME }}
                  password: ${{ secrets.SFTP_PASSWORD }}
                  remote_path: ${{ secrets.SFTP_SERVER_DIR }}
                  local_path: ./dist/*
                  sftp_only: true
                  sftpArgs: '-o ConnectTimeout=5'